# version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: library_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports: #agar tidak terekspose ke host
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

  app:
    build: .
    container_name: library_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_APPLICATION_NAME: library
      SPRINGDOC_API_DOCS_PATH: /v3/api-docs
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html
    # ports:
      # - "8080:8080"
    networks:
      - backend
      - frontend
    restart: always
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    container_name: library_nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - frontend
    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    command: certonly --webroot --webroot-path=/var/lib/letsencrypt -d 180.252.127.186
    networks:
      - frontend

volumes:
  db_data:
  certbot-etc:
  certbot-var:
  certbot:
  

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge